// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FormTypewriterController from "./form_typewriter_controller"
application.register("form-typewriter", FormTypewriterController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import InviteLinkController from "./invite_link_controller"
application.register("invite-link", InviteLinkController)
